version: '3.8'
services:
  marketing:
    build:
      context: ./marketing
      dockerfile: Dockerfile
    ports:
      - '81:8081'
    volumes:
      - ./marketing:/app
      - /app/node_modules
  container:
    build:
      context: ./container
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    volumes:
      - ./container:/app
      - /app/node_modules
    entrypoint: ["npm", "run", "build"]
  # auth:
  #   build:
  #     context: ./auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - '84:8080'
  #   volumes:
  #     - ./auth:/app
  #     - /app/node_modules

  # dashboard:
  #   build:
  #     context: ./dashboard
  #     dockerfile: Dockerfile
  #   ports:
  #     - '83:8080'
  #   volumes:
  #     - ./dashboard:/app
  #     - /app/node_modules

  npm:
    image: node:14
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./marketing:/app
      
